# Generated by Django 2.1.3 on 2018-12-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air', '0002_auto_20181203_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=25, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='public_key',
            field=models.TextField(verbose_name='Public key'),
        ),
    ]
