# Generated by Django 2.1.3 on 2018-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air', '0003_auto_20181210_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='public_key',
            field=models.TextField(unique=True, verbose_name='Public key'),
        ),
    ]
