# Generated by Django 2.1.3 on 2018-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='data_type',
            field=models.CharField(choices=[('CO', 'CO'), ('PM2.5', 'PM2.5'), ('PM10', 'PM10')], max_length=7),
        ),
    ]
